# Site
repository: ivatavuk/ivatavuk.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Ivo Vatavuk
title: Research Associate at LARICS
email: vatavuk.ivo@gmail.com
#website: https://ivatavuk.github.io/

# Dark Mode (true/false/never)
darkmode: true

# Social links
#twitter_username: facespics
github_username:  ivatavuk
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: ivo-vatavuk
# xing_username: jekyll
# pinterest_username: jekyll
youtube_username: "@ivov7194"
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Ivo and I'm . 

  I am most skilled in: <mark>C++</mark>, <mark>Python</mark> and  <mark>ROS</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Backflip Learning using a Centroidal Dynamics based Mutation-Selection Algorithm 
        description: | # this will include new lines to allow paragraphs
          ![One-legged backflip with different starting heights](/images/backflip.GIF "One-legged backflip with different starting heights"){: width="50%"}{: style="display:block; margin-left: auto; margin-right: auto;"}
      
      - layout: top-middle
        title: Precise Jump Planning using Centroidal Dynamics based Bilevel Optimization 
        description: | # this will include new lines to allow paragraphs
          ![Precise Jump Planning using Centroidal Dynamics based Bilevel Optimization](/images/jump_planning.GIF "Precise Jump Planning using Centroidal Dynamics based Bilevel Optimization"){: width="50%"}{: style="display:block; margin-left: auto; margin-right: auto;"}
      
      - layout: top-middle
        title: Task Space Model Predictive Control for Vineyard Spraying with a Mobile Manipulator 
        description: | # this will include new lines to allow paragraphs
          ![Task Space Model Predictive Control for Vineyard Spraying with a Mobile Manipulator](/images/task_space_mpc.GIF "Task Space Model Predictive Control for Vineyard Spraying with a Mobile Manipulator"){: width="50%"}{: style="display:block; margin-left: auto; margin-right: auto;"}
          
      - layout: top-middle
        title: Constrained Prioritized 3T2R Task Control for Robotic Agricultural Spraying 
        description: | # this will include new lines to allow paragraphs
          ![Constrained Prioritized 3T2R Task Control for Robotic Agricultural Spraying](/images/prioritized_spraying.GIF "Constrained Prioritized 3T2R Task Control for Robotic Agricultural Spraying"){: width="50%"}{: style="display:block; margin-left: auto; margin-right: auto;"}

      
      - layout: top-middle
        title: Prioritized Inverse Kinematics ROS Library
        link: github.com/ivatavuk/pik_ros
        # link_text: Project Website
        additional_links:
          - title:  ivatavuk/pik_ros
            icon: fab fa-github
            url: github.com/ivatavuk/pik_ros
        description: | # this will include new lines to allow paragraphs
          Prioritized inverse kinematics

  #- title: Experience # Title for the section
  #  layout: list # Type of content section (list/text)
  #  content:
  #    - layout: left
  #      title: LARICS, Faculty of Electrical Engineering and Computing, Zagreb, Croatia
  #      link: https://larics.fer.hr/
  #      # link_text: boringcompany.com
  #      sub_title: Research associate
  #      caption: 2018 - Present
  #      #quote: >
  #      #  Developing robotic
  #      #description: | # this will include new lines to allow paragraphs
  #      #    asdf

  #- title: Education # Title for the section
  #  layout: list # Type of content section (list/text)
  #  content:
  #    - layout: left
  #      title: Faculty of Electrical Engineering and Computing
  #      caption: 2018 - now
  #      sub_title: PHd Robotics
        
  #    - layout: left
  #      title: Faculty of Electrical Engineering and Computing
  #      caption: 2016 - 2018
  #      sub_title: MSc Electrical Engineering
        
  #    - layout: left
  #      title: Faculty of Electrical Engineering and Computing
  #      caption: 2013 - 2016
  #      sub_title: BSc Electrical Engineering
        

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
